### ISSUE TITLE
Mysql的表结构怎样可以快速建立？

### ISSUE THREAD

**Issue by JiangLongLiu** [tigerzioo/memos_sqlite2mysql#1]
您好！感谢您的付出和分享。
请问怎样快速建立mysql数据库结构？
有哪些方法分享？

**Comment by tigerzioo** [comment]
MySQL的安装和配置就不说了，上网自己搜一下。

创建空数据库
```
create database memos_prod
```
给数据库创建用户并把memos_prod数据库的所有权限给此用户。，用root也行，但建议给每个数据库单独创建用户。
```
CREATE USER 'memos_user'@'%' IDENTIFIED WITH mysql_native_password BY 'memos_user_password';
GRANT ALL ON memos_prod.* TO 'memos_user'@'%';
```
创建MySQL连接的docker就可以创建所有table的结构了。

Docker
```
docker run -d \
  --restart=always \
  --name memos \
  -p 5230:5230 \
  -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:stable \
  --driver mysql \
  --dsn 'memos_user:memos_user_password@tcp(MySQL_server_ip)/memos_prod'
```

Docker compose
```
version: "3.0"
services:
  memos:
    image: ghcr.io/usememos/memos:stable
    container_name: memos
    volumes:
      - ./.memos/:/var/opt/memos
    ports:
      - 5230:5230
    environment:
      MEMOS_DRIVER: mysql
      MEMOS_DSN: 'memo_user:memo_user_password@tcp(MySQL_server_ip)/memos_prod'
```
