### ISSUE TITLE
如何建立PostgreSQL空数据库table结构

### ISSUE THREAD

**Issue by tigerzioo** [tigerzioo/memos_sqlite2mysql#2]
用Docker创建PostgreSQL连接的Memos，就可以自动创建所有的数据库table结构。

创建空数据库
```
create database memos_prod
```

给数据库创建用户并把memos_prod数据库的所有权限给此用户。如果用数据库管理员用户，就不需要创建新用户了。
```
CREATE USER memo_user WITH PASSWORD 'memo_user_password';
GRANT ALL PRIVILEGES ON DATABASE memos_prod to memo_user;
```

用docker或docker-compose创建memos

Docker
```
docker run -d \
    --name memos \
    -p 5230:5230 \
    -v ~/.memos/:/var/opt/memos ghcr.io/usememos/memos:stable \
    --driver postgres \
    --dsn 'postgresql://memo_user:memo_user_password@PostgreSQL_server_ip:5432/memos_prod'
```

Docker compose
```
version: "3.0"
services:
  memos:
    image: ghcr.io/usememos/memos:stable
    container_name: memos
    volumes:
      - ./.memos/:/var/opt/memos
    ports:
      - 5230:5230
    environment:
      MEMOS_DRIVER: postgres
      MEMOS_DSN: postgresql://memo_user:memo_user_password@PostgreSQL_server_ip:5432/memos_prod
```
